name: Backend

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  Build_AzureFunctions:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET v7.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        dotnet-quality: 'preview'
        
        
    - name: Setup .NET Core v3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Remove `#error` From CognitiveServicesConstants.cs
      run: |
        CognitiveServicesConstants=`find . -name CognitiveServicesConstants.cs`
        echo CognitiveServicesConstants: $CognitiveServicesConstants

        sed -i '' "s/#error/\/\/#error/g" "$CognitiveServicesConstants"

    - name: Remove `#error` From SignalRConstants.cs
      run: |
        SignalRConstants=`find . -name SignalRConstants.cs`
        echo SignalRConstants: $SignalRConstants

        sed -i '' "s/#error/\/\/#error/g" "$SignalRConstants"

    - name: Build Functions
      run: dotnet build ./TextMood.Functions/ -c Release

  Build_SignalR:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET v6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Setup .NET Core v3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Remove `#error` From CognitiveServicesConstants.cs
      run: |
        CognitiveServicesConstants=`find . -name CognitiveServicesConstants.cs`
        echo CognitiveServicesConstants: $CognitiveServicesConstants

        sed -i '' "s/#error/\/\/#error/g" "$CognitiveServicesConstants"

    - name: Remove `#error` From SignalRConstants.cs
      run: |
        SignalRConstants=`find . -name SignalRConstants.cs`
        echo SignalRConstants: $SignalRConstants

        sed -i '' "s/#error/\/\/#error/g" "$SignalRConstants"

    - name: Build SignalR
      run: dotnet build ./TextMood.SignalR/ -c Release
